### ISSUE TITLE
Windows Defenderが反応してしまいます。

### ISSUE THREAD

**Issue by izenizen** [radi-sh/BonDriver_BDA#6]
いつも、素晴らしいドライバをありがとうございます。
この度、2月2日バージョンをReleaseからzipをダウンロードしたところ、Antivirusではねられてしまいました。
なにか、Trojanと似たコードをこの中にいれておられるのでしょうか？
もしRadi-shさんのほうでも別のウイルスチェックをされておられれば、ご確認いただきますとありがたいです。

https://github.com/radi-sh/BonDriver_BDA/releases/download/Release-20190202/BonDriver_BDA-2019-02-02.zip

Trojan:Win32/Bitrep.A
Severe |Detected with Windows Defender Antivirus

**Comment by khisanag** [comment]
自分もWin10Proでウイルス検出とかでダウンロードできず、Macにダウンロードして、Bitdefenderで解凍後のファイルをチェックしてみたら、4つほど消されてしまいました。ご確認いただけると幸いです。

Gen:Variant.Ursu.380587
 
/Users/.../Downloads/BonDriver_BDA-2019-02-02/x86/Release-XP/BonDriver_BDA.dll
 
Deleted
 
Gen:Variant.Ursu.380587
 
/Users/.../Downloads/BonDriver_BDA-2019-02-02/x86/Release/BonDriver_BDA.dll
 
Deleted
 
Gen:Variant.Ursu.380587
 
/Users/.../Downloads/BonDriver_BDA-2019-02-02/x86/Release_Static/BonDriver_BDA.dll
 
Deleted
 
Trojan.GenericKD.31688137
 
/Users/.../Downloads/BonDriver_BDA-2019-02-02/x86/Release-XP_Static/BonDriver_BDA.dll
 
Deleted

**Comment by radi-sh** [comment]
--- 以下、 Windows Defender ATP team より ---
bondriver_bda.dll
Submission ID: 782c7bbe-5c6a-4b69-82cc-1721f4db1b86
Status: Completed
Submitted by: ***@***
Submitted: Feb 26, 2019 9:41:59
User Opinion: Incorrect detection
Analyst comments:
                We have removed the detection.  Please follow the steps below to clear cached detection and obtain the latest malware definitions.
     1. Open command prompt as administrator and change directory to c:\Program Files\Windows Defender 
     2. Run “MpCmdRun.exe -removedefinitions -dynamicsignatures”
     3. 3. Run “MpCmdRun.exe -SignatureUpdate” 
Alternatively, the latest definition is available for download here: https://www.microsoft.com/en-us/wdsi/definitions
Thank you for contacting Microsoft.

**Comment by izenizen** [comment]
大変迅速なご対応をいただき大変ありがとうございます。
早速利用させていただきます。

**Comment by khisanag** [comment]
ありがとうございました!
今後ともよろしくお願いします。
