### ISSUE TITLE
How to delivery the TS id ?

### ISSUE THREAD

**Issue by Davin622** [radi-sh/BonDriver_BDA#7]
Hi ,
I am making a  drivers of the isdb-s/s3 device. i want to support the TVtest player. 
now i am very confused that how to delivery the TS id to the drivers. which interface your used?

Thanks

**Comment by radi-sh** [comment]
Hi Davin622.
There is an IDVBTuneRequest::put_TSID method for deliver the TSID from application to the driver.
I think it is translated to IBDA_TransportStreamSelector::SetTSID by the network provider.
However, as far as I know, the driver in which it is implemented is very rare.

**Comment by Davin622** [comment]
sorry for delay reply.
thanks for your answer. i am the TBS  product drivers engineer. i have seen you added the special interface for our product. 
now we have a product of the ISDB-S, becuase BDA framework's Node type have not suppurt the ISDB-S. so i use the node type of "KSNODE_BDA_QAM_DEMODULATOR" .  it work way like the dvbs mode,  i add the private interface to set the ts id 
"KSPROPERTY_BDA_SETTSID = 96,  // added 20190704 for ISDB-S/S3 for BonBDA drivers"
This is the seting function on "TBSSpecials.cpp"
const HRESULT CTBSSpecials::SetTSid(long TSID)     //add 20190715 by Davin zhang TBS
{
	DWORD TypeSupport=0;
	HRESULT hr;
	

	hr = m_pPropsetTunerPin->QuerySupported(KSPROPSETID_BdaTunerExtensionProperties,
			KSPROPERTY_BDA_SETTSID,	&TypeSupport);
	if FAILED(hr)
			return E_NOINTERFACE;
	hr = m_pPropsetTunerPin->set(KSPROPSETID_BdaTunerExtensionProperties,
					KSPROPERTY_BDA_SETTSID,
					&TSID,sizeof(long),
					&TSID,sizeof(long),
					&TypeSupport);
					
	if FAILED(hr)
		return E_NOTIMPL;
	
	return S_OK;
}

Could you help me add the interface on your github, and make this interface work on the BonDrivers ?
Thanks&Best Regards

**Comment by radi-sh** [comment]
I see, I'll do it!

**Comment by Davin622** [comment]
thanks

**Comment by PlexUsers** [comment]
Hi,
I'm testing the newest BonDriver_BDA, after building it.
When I set UseSpecial="TBS", Bon_Driver.dll fails with exception error.
"CComQIPtr<IKsPropertySet>" seems a problem here.
Please someone test it, too.

**Comment by PlexUsers** [comment]
To build TBS.dll, please add 
void CTBSSpecials::Release(void)
{
	delete this;
}

**Comment by PlexUsers** [comment]
IKsPropertySet interface maybe a problem now.
